### ISSUE TITLE
Confidence Proportion and Estimate Size Needed using 95% confidence

### ISSUE THREAD

**Issue by livcara123** [livcara123/Group-5---Unit-3#2]

**Comment by livcara123** [comment]
Hi Adam, please complete these two items for the project

**Comment by AdamCaruso25** [comment]
I will work on them as soon as possible

**Comment by AdamCaruso25** [comment]
Hey, I just completed both the confidence proportion and the size needed using 95% confidence. I will upload them to the Powerpoint right now.

**Comment by livcara123** [comment]
Ok thank you for completing them!
